## Topic Modelling (LDA - Gensim LDA Mallet) & Content Base Recommendation (LDA + TF-IDF)

In [13]:
# run this statement only once to install Rake
!pip install rake_nltk

zsh:1: command not found: pip

In [14]:
import numpy as np
import pandas as pd
from rake_nltk import Rake
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

import re, nltk, spacy, gensim
from nltk.tokenize import ToktokTokenizer
from nltk.stem import wordnet
from nltk.corpus import stopwords
from string import punctuation

import pandas as pd
import glob


import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.stem import WordNetLemmatizer,PorterStemmer
from nltk.corpus import stopwords
import re

### Step 1: Read in and analyse the data

In [15]:


path = r'./dataSmall/' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)



# df = pd.read_csv('Kickstarter057.csv')

df = frame
df

,backers_count,blurb,category,converted_pledged_amount,country,country_displayable_name,created_at,creator,currency,currency_symbol,...,slug,source_url,spotlight,staff_pick,state,state_changed_at,static_usd_rate,urls,usd_pledged,usd_type
0,13,'Sects' is a comedy webseries - about two girl...,"{""id"":33,""name"":""Webseries"",""slug"":""film & vid...",556,US,the United States,1426711317,"{""id"":1167510066,""name"":""SECTS"",""is_registered...",USD,$,...,sects-pilot,https://www.kickstarter.com/discover/categorie...,True,False,successful,1428510545,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",556.000000,international
1,207,Terrence McNallyâ€™s pioneering 5-decades in the...,"{""id"":30,""name"":""Documentary"",""slug"":""film & v...",42766,US,the United States,1489540002,"{""id"":1365145996,""name"":""Jeff Kaufman and Marc...",USD,$,...,every-act-of-life,https://www.kickstarter.com/discover/categorie...,True,True,successful,1511366769,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",42766.000000,international
2,0,A romantic Comedy of falling for your true lov...,"{""id"":300,""name"":""Romance"",""slug"":""film & vide...",0,US,the United States,1464218765,"{""id"":728939759,""name"":""Macleish Day"",""is_regi...",USD,$,...,once-with-maggie,https://www.kickstarter.com/discover/categorie...,False,False,canceled,1470328862,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",0.000000,international
3,0,I,"{""id"":301,""name"":""Science Fiction"",""slug"":""fil...",0,US,the United States,1466370982,"{""id"":575672815,""name"":""Edgar Cav - Director (...",USD,$,...,adrift-3,https://www.kickstarter.com/discover/categorie...,False,False,canceled,1466560506,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",0.000000,international
4,70,It's hard being Gavin. Especially if you're Ga...,"{""id"":292,""name"":""Comedy"",""slug"":""film & video...",23404,AU,Australia,1475582845,"{""id"":1788056248,""name"":""Mark Kilmurry & Owen ...",AUD,$,...,being-gavin,https://www.kickstarter.com/discover/categorie...,False,False,failed,1482314551,0.734012,"{""web"":{""project"":""https://www.kickstarter.com...",23666.024254,international
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3676,4,"Inspired by Burning Man, I am building a water...","{""id"":258,""name"":""Architecture"",""slug"":""design...",65,US,the United States,1405433682,"{""id"":1449913350,""name"":""Mike Warren"",""slug"":""...",USD,$,...,bug-free-monkey-hut,https://www.kickstarter.com/discover/categorie...,False,False,failed,1408030621,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",65.000000,international
3677,124,International collaboration by Yoshiko Chuma &...,"{""id"":6,""name"":""Dance"",""slug"":""dance"",""positio...",11462,US,the United States,1328645073,"{""id"":1403167449,""name"":""Yoshiko Chuma"",""is_re...",USD,$,...,love-story-palestine,https://www.kickstarter.com/discover/categorie...,True,False,successful,1335931141,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",11462.450000,international
3678,57,'STRUM' A vibrant dance performance celebratin...,"{""id"":254,""name"":""Performances"",""slug"":""dance/...",4154,US,the United States,1391542191,"{""id"":1928397609,""name"":""UPside Dance Company""...",USD,$,...,upside-dance-presents-strum-with-composer-mark...,https://www.kickstarter.com/discover/categorie...,True,True,successful,1396421940,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",4154.000000,international
3679,48,I want to support people that are experiencing...,"{""id"":343,""name"":""Candles"",""slug"":""crafts/cand...",2116,GB,the United Kingdom,1591768463,"{""id"":1366582721,""name"":""Jessica Cronshaw"",""sl...",GBP,Â£,...,agni-community-candle-making-training,https://www.kickstarter.com/discover/categorie...,True,True,successful,1594369608,1.271328,"{""web"":{""project"":""https://www.kickstarter.com...",2137.102570,international
3680,48,Bringing contemporary dance to the street chil...,"{""id"":254,""name"":""Performances"",""slug"":""dance/...",3169,US,the United States,1409713116,"{""id"":260280584,""name"":""Nicole Corea"",""is_regi...",USD,$,...,spreading-hope-through-dance-to-rwandan-street...,https://www.kickstarter.com/discover/categorie...,True,True,successful,1413329736,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",3169.000000,international

In [16]:
def extract_cat(text):
    text = text.split(",")
    
    text = text[1] + " " +text[2]
    

    text = text.replace ("/", " ")
    
    
    text = text.replace ("name", "")
    text = text.replace ("slug", "")
    
    text = text.replace ('"', "")
    text = text.replace ('{', "")
    text = text.replace (':', "")
    
    text = text.lower()
    text = re.sub(r"\'\n", " ", text)
    text = re.sub(r"\'\xa0", " ", text)
    text = re.sub('\s+', ' ', text) # matches all whitespace characters
    text = text.strip(' ')
    return text



df['category'] = df['category'].apply(lambda x: extract_cat(x))


df.head()

,backers_count,blurb,category,converted_pledged_amount,country,country_displayable_name,created_at,creator,currency,currency_symbol,...,slug,source_url,spotlight,staff_pick,state,state_changed_at,static_usd_rate,urls,usd_pledged,usd_type
0,13,'Sects' is a comedy webseries - about two girl...,webseries film & video webseries,556,US,the United States,1426711317,"{""id"":1167510066,""name"":""SECTS"",""is_registered...",USD,$,...,sects-pilot,https://www.kickstarter.com/discover/categorie...,True,False,successful,1428510545,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",556.000000,international
1,207,Terrence McNallyâ€™s pioneering 5-decades in the...,documentary film & video documentary,42766,US,the United States,1489540002,"{""id"":1365145996,""name"":""Jeff Kaufman and Marc...",USD,$,...,every-act-of-life,https://www.kickstarter.com/discover/categorie...,True,True,successful,1511366769,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",42766.000000,international
2,0,A romantic Comedy of falling for your true lov...,romance film & video romance,0,US,the United States,1464218765,"{""id"":728939759,""name"":""Macleish Day"",""is_regi...",USD,$,...,once-with-maggie,https://www.kickstarter.com/discover/categorie...,False,False,canceled,1470328862,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",0.000000,international
3,0,I,science fiction film & video science fiction,0,US,the United States,1466370982,"{""id"":575672815,""name"":""Edgar Cav - Director (...",USD,$,...,adrift-3,https://www.kickstarter.com/discover/categorie...,False,False,canceled,1466560506,1.000000,"{""web"":{""project"":""https://www.kickstarter.com...",0.000000,international
4,70,It's hard being Gavin. Especially if you're Ga...,comedy film & video comedy,23404,AU,Australia,1475582845,"{""id"":1788056248,""name"":""Mark Kilmurry & Owen ...",AUD,$,...,being-gavin,https://www.kickstarter.com/discover/categorie...,False,False,failed,1482314551,0.734012,"{""web"":{""project"":""https://www.kickstarter.com...",23666.024254,international

In [17]:

df = df[['name','category','blurb']]
df.head()

,name,category,blurb
0,'Sects' Pilot,webseries film & video webseries,'Sects' is a comedy webseries - about two girl...
1,Every Act Of Life,documentary film & video documentary,Terrence McNallyâ€™s pioneering 5-decades in the...
2,"Once, With Maggie (Canceled)",romance film & video romance,A romantic Comedy of falling for your true lov...
3,I (Canceled),science fiction film & video science fiction,I
4,Being Gavin,comedy film & video comedy,It's hard being Gavin. Especially if you're Ga...

### Step 2a: Data pre-processing

In [18]:

lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer() 

def preprocess(sentence):
    sentence=str(sentence)
    sentence = sentence.lower()
    sentence=sentence.replace('{html}',"") 
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', sentence)
    rem_url=re.sub(r'http\S+', '',cleantext)
    rem_num = re.sub('[0-9]+', '', rem_url)
    tokenizer = RegexpTokenizer(r'\w+')
    tokens = tokenizer.tokenize(rem_num)  
    filtered_words = [w for w in tokens if len(w) > 2 if not w in stopwords.words('english')]
    stem_words=[stemmer.stem(w) for w in filtered_words]
    lemma_words=[lemmatizer.lemmatize(w) for w in stem_words]
    return " ".join(filtered_words)


df['blurb']=df['blurb'].map(lambda s:preprocess(s))

<ipython-input-18-d7ee41603926>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['blurb']=df['blurb'].map(lambda s:preprocess(s))

In [19]:
df.head()

,name,category,blurb
0,'Sects' Pilot,webseries film & video webseries,sects comedy webseries two girls accidentally ...
1,Every Act Of Life,documentary film & video documentary,terrence mcnally pioneering decades american t...
2,"Once, With Maggie (Canceled)",romance film & video romance,romantic comedy falling true love tight circum...
3,I (Canceled),science fiction film & video science fiction,
4,Being Gavin,comedy film & video comedy,hard gavin especially gavin comedy feature fil...

In [20]:
df['category_processed'] = ""


for index, row in df.iterrows():
    cat = row['category']
    
    # instantiating a Rake object
    # by default it uses english stopwords from NLTK (natural language tool kit)
    # and discards all puntuation characters
    r = Rake()

    # extracting the keywords from the text by passing plot 
    r.extract_keywords_from_text(cat)

    # getting the dictionary whith key words and their scores
    key_words_dict_scorestwo = r.get_word_degrees()
    
    # assigning the key words to the new column
    row['category_processed'] = [w for w in key_words_dict_scorestwo.keys()]

<ipython-input-20-0a6530d97d4d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['category_processed'] = ""

In [21]:
df.head()

,name,category,blurb,category_processed
0,'Sects' Pilot,webseries film & video webseries,sects comedy webseries two girls accidentally ...,"[webseries, film, video]"
1,Every Act Of Life,documentary film & video documentary,terrence mcnally pioneering decades american t...,"[documentary, film, video]"
2,"Once, With Maggie (Canceled)",romance film & video romance,romantic comedy falling true love tight circum...,"[video, romance, film]"
3,I (Canceled),science fiction film & video science fiction,,"[science, fiction, film, video]"
4,Being Gavin,comedy film & video comedy,hard gavin especially gavin comedy feature fil...,"[comedy, film, video]"

In [22]:
df['blurb_processed'] = ""

for index, row in df.iterrows():
    desc = row['blurb']
    
    # instantiating a Rake object
    # by default it uses english stopwords from NLTK (natural language tool kit)
    # and discards all puntuation characters
    r = Rake()

    # extracting the keywords from the text by passing plot 
    r.extract_keywords_from_text(str(desc))

    # getting the dictionary whith key words and their scores
    key_words_dict_scores = r.get_word_degrees()
    
    # assigning the key words to the new column
    #stemming
#     row['desc_stem'] = [stemmer.stem(w) for w in key_words_dict_scores.keys()]
    row['blurb_processed'] = [w for w in key_words_dict_scores.keys()]
    
df.head()

<ipython-input-22-923fd48c99d1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['blurb_processed'] = ""

,name,category,blurb,category_processed,blurb_processed
0,'Sects' Pilot,webseries film & video webseries,sects comedy webseries two girls accidentally ...,"[webseries, film, video]","[sects, comedy, webseries, two, girls, acciden..."
1,Every Act Of Life,documentary film & video documentary,terrence mcnally pioneering decades american t...,"[documentary, film, video]","[terrence, mcnally, pioneering, decades, ameri..."
2,"Once, With Maggie (Canceled)",romance film & video romance,romantic comedy falling true love tight circum...,"[video, romance, film]","[romantic, comedy, falling, true, love, tight,..."
3,I (Canceled),science fiction film & video science fiction,,"[science, fiction, film, video]",[]
4,Being Gavin,comedy film & video comedy,hard gavin especially gavin comedy feature fil...,"[comedy, film, video]","[hard, gavin, especially, comedy, feature, fil..."

In [23]:
df = df[['name', 'category_processed', 'blurb_processed']]

df.head()

,name,category_processed,blurb_processed
0,'Sects' Pilot,"[webseries, film, video]","[sects, comedy, webseries, two, girls, acciden..."
1,Every Act Of Life,"[documentary, film, video]","[terrence, mcnally, pioneering, decades, ameri..."
2,"Once, With Maggie (Canceled)","[video, romance, film]","[romantic, comedy, falling, true, love, tight,..."
3,I (Canceled),"[science, fiction, film, video]",[]
4,Being Gavin,"[comedy, film, video]","[hard, gavin, especially, comedy, feature, fil..."

### Step 3: Create word representation via a bag of words 

Using the values from the df columns

In [24]:
# name should be omitted from bag of words creation
columns = df.columns[1:]


df['bag_of_words'] = ''

for index, row in df.iterrows():
    words = ''
    for col in columns:
        if col != 'bag_of_words':
            # to convert the list into a string of words separated by a space
            words = words + ' '.join(row[col])+ ' '
        else:
            words = words + row[col]+ ' '
    row['bag_of_words'] = words

# let's keep only the title and the bag of words in the dataframe
df.head()

,name,category_processed,blurb_processed,bag_of_words
0,'Sects' Pilot,"[webseries, film, video]","[sects, comedy, webseries, two, girls, acciden...",webseries film video sects comedy webseries tw...
1,Every Act Of Life,"[documentary, film, video]","[terrence, mcnally, pioneering, decades, ameri...",documentary film video terrence mcnally pionee...
2,"Once, With Maggie (Canceled)","[video, romance, film]","[romantic, comedy, falling, true, love, tight,...",video romance film romantic comedy falling tru...
3,I (Canceled),"[science, fiction, film, video]",[],science fiction film video
4,Being Gavin,"[comedy, film, video]","[hard, gavin, especially, comedy, feature, fil...",comedy film video hard gavin especially comedy...

In [25]:
df.drop(columns = ['category_processed'], inplace = True)
df.drop(columns = ['blurb_processed'], inplace = True)
df.head()

,name,bag_of_words
0,'Sects' Pilot,webseries film video sects comedy webseries tw...
1,Every Act Of Life,documentary film video terrence mcnally pionee...
2,"Once, With Maggie (Canceled)",video romance film romantic comedy falling tru...
3,I (Canceled),science fiction film video
4,Being Gavin,comedy film video hard gavin especially comedy...

### Step 4: Create cosine similarity matrix

In [26]:
# instantiating and generating the count matrix using CountVectorizer
count = CountVectorizer()
count_matrix = count.fit_transform(df['bag_of_words'])

In [27]:
# generating the cosine similarity matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim)

[[1.         0.13867505 0.20801257 ... 0.         0.         0.        ]
 [0.13867505 1.         0.125      ... 0.         0.         0.        ]
 [0.20801257 0.125      1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.35805744]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.35805744 0.         1.        ]]

### Step 5: Create and Run the model (recommender)

In [28]:
# creating a Series for the movie titles and corresponding indexes
indices = pd.Series(df['name'])
indices[:5]
df = df[['name', 'bag_of_words']]

df.head()

,name,bag_of_words
0,'Sects' Pilot,webseries film video sects comedy webseries tw...
1,Every Act Of Life,documentary film video terrence mcnally pionee...
2,"Once, With Maggie (Canceled)",video romance film romantic comedy falling tru...
3,I (Canceled),science fiction film video
4,Being Gavin,comedy film video hard gavin especially comedy...

In [29]:
def recommendations(name, cosine_sim = cosine_sim):
    
    recommended = []
    
    # getting the index of the movie with the given title
    idx = indices[indices == name].index[0]

    # creating a Series with the similarity scores in descending order
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)

    # getting the indexes of the 10 most similar movies
    top_10_indexes = list(score_series.iloc[1:12].index)
    
    # populating the list with the titles of the best 10 matching movies
    for i in top_10_indexes:
        recommended.append(list(df['name'])[i])
        
    return recommended

In [30]:
recommendations("Ghetto Bird Short Film - Festival Fundraiser")

['Wotever DIY Film Festival',
 'Delicious Poison (2019)',
 'Sleep With Sadie',
 'One Afternoon in the Woods - Short Film',
 'Fallout: A Means to an End (Canceled)',
 'Casa VacÃ­a',
 'Wanderlust',
 'Chicago South Asian Film Festival 2017',
 'Merde',
 'Kill File',
 'Oat Milk']

In [236]:
text = "Quotes from Far Far Away: Part 2 - An Enamel Pin Series"

df.loc[df['name'] == text]

Empty DataFrame
Columns: [backers_count, blurb, category, converted_pledged_amount, country, country_displayable_name, created_at, creator, currency, currency_symbol, currency_trailing_code, current_currency, deadline, disable_communication, friends, fx_rate, goal, id, is_backing, is_starrable, is_starred, launched_at, location, name, permissions, photo, pledged, profile, slug, source_url, spotlight, staff_pick, state, state_changed_at, static_usd_rate, urls, usd_pledged, usd_type]
Index: []

[0 rows x 38 columns]

In [228]:
id = 9485
pd.set_option("display.max_colwidth", None)
frame[id:id+1]

,backers_count,blurb,category,converted_pledged_amount,country,country_displayable_name,created_at,creator,currency,currency_symbol,...,slug,source_url,spotlight,staff_pick,state,state_changed_at,static_usd_rate,urls,usd_pledged,usd_type
9485,58,My debut album,music music,3701,ES,Spain,1597827181,"{""id"":1977426607,""name"":""Melanie Brennan"",""slug"":""melbrennan-halflives"",""is_registered"":null,""is_email_verified"":null,""chosen_currency"":null,""is_superbacker"":null,""avatar"":{""thumb"":""https://ksr-ugc.imgix.net/assets/030/317/774/cc61ace548be6db353d6659367e1cda3_original.jpg?ixlib=rb-2.1.0&w=40&h=40&fit=crop&v=1598601683&auto=format&frame=1&q=92&s=5fc480a5781961f246149362eb4ebb3d"",""small"":""https://ksr-ugc.imgix.net/assets/030/317/774/cc61ace548be6db353d6659367e1cda3_original.jpg?ixlib=rb-2.1.0&w=80&h=80&fit=crop&v=1598601683&auto=format&frame=1&q=92&s=808d7b21cc04ad656eed47afb258933e"",""medium"":""https://ksr-ugc.imgix.net/assets/030/317/774/cc61ace548be6db353d6659367e1cda3_original.jpg?ixlib=rb-2.1.0&w=160&h=160&fit=crop&v=1598601683&auto=format&frame=1&q=92&s=2a19ebde9f00b3cbe1dc9a1194262b10""},""urls"":{""web"":{""user"":""https://www.kickstarter.com/profile/melbrennan-halflives""},""api"":{""user"":""https://api.kickstarter.com/v1/users/1977426607?signature=1616139369.cf7fff7b427c4b32a35a574d16254f3c1d6fe781""}}}",EUR,â‚¬,...,half-lives,https://www.kickstarter.com/discover/categories/music,True,False,successful,1601719200,1.190325,"{""web"":{""project"":""https://www.kickstarter.com/projects/melbrennan-halflives/half-lives?ref=discovery_category_newest"",""rewards"":""https://www.kickstarter.com/projects/melbrennan-halflives/half-lives/rewards""}}",3760.235317,international

In [118]:
frame
frameTwo = df

In [121]:
frameTwo['bag_of_words']

0        books publishing children find happens albert ...
1        letterpress publishing following success hasti...
2        periodicals publishing join amazing journey im...
3         anthologies publishing anthology queer witchery
4        poetry publishing written chronically ill girl...
                               ...
40308    gaming hardware games unique immersion using w...
40309    drinks food autoimmuni tea california based co...
40310    vegan food range cauliflower crust pizzas reta...
40311    food trucks madhuri means inner beauty sweetne...
40312    community gardens food help founder food lawns...
Name: bag_of_words, Length: 40313, dtype: object

In [122]:
test = df['blurb'].str.cat(sep=' ')

In [126]:
print(test[1:400])
hello = test.split(" ")

ooks publishing children find happens albert decides play food takes high flying adventure outer space  letterpress publishing following success hastings leonard guide book creating sneeky peek rye  periodicals publishing join amazing journey impacting million children  anthologies publishing anthology queer witchery  poetry publishing written chronically ill girl commenting ups downs craziness l

In [128]:
print (len(hello))

562749

In [ ]:
Lang Dance Senior Show Lang Dance Senior Show